import type { Metadata } from "next";
import { Noto_Sans, Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

import Providers from "./providers";
import Navbar from "@/src/components/Navbar";
import Footer from "@/src/components/Footer";
import CookieBanner from "@/src/components/common/CookieBanner";

const notoThai = Noto_Sans_Thai({
  subsets: ["thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-thai",
  display: "swap",
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-latin",
  display: "swap",
});

export const metadata: Metadata = {
  title: "RentFlow - เช่ารถง่าย แค่ปลายนิ้ว",
  description: "Generated by create next app",
  icons: {
    icon: "/redis.svg",
    shortcut: "/redis.svg",
    apple: "/redis.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={`${notoThai.variable} ${notoSans.variable}`}>
      <body className="font-thai">
        <Providers>
          <Navbar />
          {children}
          <Footer />
          <CookieBanner />
        </Providers>
      </body>
    </html>
  );
}
